# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1914e30548a07cb382feca7108ee35d8e73e3c710b813a6340ba70cf5c88d0459159d8772dc6b8926ddf8b254afd206ce1222d5c8cecd7c1cea9db8efded03e

test:
  secret_key_base: 6376d1ab03bd4395fe3553bcf0a59b32d64013b0431b169555f59ff0b25b9809ce9d26f70655eab3b9f5236bb1363abeb1075ebaba7cfb6c2f956057cc890c5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
